name: Integration Tests

on:
  pull_request:
    branches: ["main"]
    paths:
      - "task_api/**"

jobs:
  compose-it:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Pip
        uses: actions/cache@v4.2.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Create Database
        run: docker compose up -d db

      - name: Run Integration Tests
        run: pytest -q -m "integration"

      - name: Upload Log Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: log-${{ github.run_id }}-${{ matrix.python-version }}
          path: pytest.log
