name: Security

on:
  pull_request:
    branches: ["main"]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      # - name: Set up Python
      #   uses: actions/setup-python@v5.6.0
      #   with:
      #     python-version: "3.11"

      - name: Audit
        uses: lazy-actions/pip-audit-action@v1
        with:
          type: pip
