name: Security

on:
  pull_request:
    branches: ["main"]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Pip Audit
        uses: lazy-actions/pip-audit-action@v1
        with:
          type: pip
      
      - name: Container Scan
        uses: crazy-max/ghaction-container-scan@v3.2.0
        with:
          dockerfile: ./Dockerfile
          severity: HIGH
          annotations: true
         
